### ISSUE TITLE
How can create fix header with angular-iscroll and angular-snap

### ISSUE THREAD

**Issue by hemedani** [mtr/angular-iscroll#14]
Hi i have a question before trying this cool directive ... (forgive me)
I want's to know how can we create `fixed` position like header in the core-layout but with snap.js 
[something like this](http://jsfiddle.net/frank_o/jd2du1ga/)
but in real project I'm using the angular-snap.js with `<snap-content>` directive
however i want's to know how can i use this features 
`<header data-role="header" data-position="fixed">`
in angular version of iscroll
tank you so much ...

**Comment by mtr** [comment]
Hi @hemedani,

I'm sorry, but I don't have any experience in combining angular-iscroll with angular-snap, nor do I know if it would be a fruitful combination.  In core-layout I implemented support for both drawers on both the left and right hand side of the screen.  Assuming that what you want is the drawer effect, what is the particular different behavior you are aiming at?

**Comment by hemedani** [comment]
Hi @mtr 
In snap.js we can easily drag page to left and right for drawer I don't know we can drag page to left and right in iscroll or not.
in angular-snap we have huge customization like closing drawers when route is changing and ...
but i find two bugs in snap one for scrolling the drawers when the size of display in very small to fix this bug in snap doc says [using iscroll library](https://github.com/jakiestfu/Snap.js/#faq)
and another bug is we can not use `position fixed` in `<snap-content>` so I'm fixing this bug whit jquery scroller.
I just want's to know how can i use this feature `data-position="fixed"` in angular-iscroll
tanx man
