### ISSUE TITLE
scrollbar do not show

### ISSUE THREAD

**Issue by nhuthuynh** [mtr/angular-iscroll#18]
I inspect the html of iscroll to find scrollbar element but it seem do not creating scrollbar. The question is how can i add scrollbar ?

**Comment by George-Payne** [comment]
You add scrollbars: true to the options. see [here](https://github.com/mtr/angular-iscroll#configuration).

```
<div iscroll="{scrollbars: true}">
```

multiple options:

```
<div iscroll="{scrollbars: true, interactiveScrollbars: true}">
```

or you could configure your defaults. see [here](https://github.com/mtr/angular-iscroll#globally-configuring-the-directives-default-options).

```
iScrollServiceProvider.configureDefaults({scrollbars: true, interactiveScrollbars: true});
```

See more options here: 

http://iscrolljs.com/#scrollbars
