### ISSUE TITLE
Support zoom option?

### ISSUE THREAD

**Issue by Ridermansb** [mtr/angular-iscroll#30]
This support zoom on cordova project?

I try to use like..

**Import angular module**

``` javascript
import 'angular-iscroll';
angular.module('app', ['ngAria', 'angular-iscroll']) ..
```

**Apply directive**

``` html
<img iscroll="{}" class="zoom" ng-if="question.image" ng-src="{{question.image | showAsBase64}}" alt="Imagem motivadora" style="width: 100%">
```

**And css**

``` css
img.zoom { -webkit-transform:translate3d(0,0,0) }
```

When I run the app.. and try to zoom on the image nothing happens

> The image is base64

**Comment by mtr** [comment]
I am sorry, I haven't tried to use this with zooming in Cordova.
