### ISSUE TITLE
how to create Pull down to refresh and Pull up to request more

### ISSUE THREAD

**Issue by jrmendz** [mtr/angular-iscroll#36]
I was using ionics refresher and ionic infinite scroll before but due to poor performance i needed to change it with iScroll
`<ion-refresher on-refresh="doRefresh()"></ion-refresher>`
`<ion-infinite-scroll ng-if="page <= last_page" on-infinite="loadMore()" distance="20%"></ion-infinite-scroll>`

**Comment by xiangyu1225** [comment]
https://github.com/mtr/angular-iscroll/issues/33
希望有帮助

**Comment by mtr** [comment]
This seems to be a purely IScroll, not `iscroll-angular`, related question.
