### ISSUE TITLE
accessing events? 

### ISSUE THREAD

**Issue by iclimb513** [mtr/angular-iscroll#38]

**Comment by iclimb513** [comment]
I don't get it.  I need something to happen when someone has scrolled to the end.  What do you do?

None of these work:

`<div class="wrapper"  iscroll  onScrollEnd="myfunction()">
<div class="wrapper"  iscroll  iscroll-onScrollEnd="myfunction()">
<div class="wrapper"  iscroll  scrollEnd="myfunction()">
<div class="wrapper"  iscroll  onScrollEnd="myfunction()">`

Someone please explain what you have to do to make use of the events?  Also, I don't understand what use there is for this:

iscroll-instance="instance"

ok, now what?  What use is that exactly?  Can I look at that and access properties of it in the controller?

Documentation tells me nothing.  Not all of us are experts.

**Comment by artaommahe** [comment]
@iclimb513 just pass event handlers to directive property

```
<div iscroll="{ onScrollEnd: $ctrl.onScrollEnd }">
```

where `$ctrl.onScrollEnd` is controller public method

available events (dont forget to add on-prefix and capitalize first letter)

```
            'beforeScrollStart',
            'scrollCancel',
            'scrollStart',
            'scroll',
            'scrollEnd',
            'flick',
            'zoomStart',
            'zoomEnd'
```

**Comment by mtr** [comment]
Thanks for answering this, @artaommahe.
