### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rdesimone** [mtr/angular-iscroll#4]
The demo looks great. Do you have a documentation? Thanks!

**Comment by mtr** [comment]
Hi, @rdesimone.  I haven't gotten around to writing the documentation yet.  What parts would you like to have documented?  This [angular-iscroll](https://github.com/mtr/angular-iscroll) module, or the [core-layout](https://github.com/mtr/core-layout) module and/or demo?

**Comment by rdesimone** [comment]
For angular-iscroll - thanks a lot!

**Comment by rdesimone** [comment]
At the end I would like to have a scrollable container where iScroll can be switched on/off  - for iOS with iScroll, otherwise native scrolling.

**Comment by mtr** [comment]
I've now added a bit of [usage documentation](https://github.com/mtr/angular-iscroll/blob/master/README.md#usage) to the [README.md](https://github.com/mtr/angular-iscroll/blob/master/README.md).  I've also added a comment in there about how one can solve the issue you describe above.  I hope it is helpful.
