### ISSUE TITLE
IScroll is not a constructor

### ISSUE THREAD

**Issue by patfrat** [mtr/angular-iscroll#40]
I have this error when i include angular-iscroll and try to use it
IScroll is not a constructor
at this line https://github.com/mtr/angular-iscroll/blob/master/src/lib/angular-iscroll.js#L296

window reference is missing

``` javascript
var instance = new window.IScroll(element[0], options.iScroll), ...
```

**Comment by mtr** [comment]
I am sorry for this awfully long delay, but that is probably caused by not having included the IScroll library before trying to initialize the `angular-iscroll` module.
