### ISSUE TITLE
Dynamic instance name

### ISSUE THREAD

**Issue by NeedNap** [mtr/angular-iscroll#8]
I can't use dynamic instance name. 
What can I do? 

If I want to use many nested iScroll (generated by ng-repeat directive) and give them an instance name, I can't see the instance in my controller class!

What can I do?
Thanks

**Comment by mtr** [comment]
Hi, @NeedNap.

Can you please create a minimalistic example of this, for example on [Plunker](http://plnkr.co/), and share that with me, so that I can see exactly what your problem is and test for my self how it might be solved?
